version: '3.8'
services:

  pma:
    container_name: pma
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:8080'
    env_file:
      - ".env"
    networks:
      - local

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: db
    expose:
      - "3306"
    networks:
      - local
    volumes:
      - "./docker/mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

networks:
  local: